on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4
      - uses: actions/setup-node@master

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set up .env
        run: |
          echo "DB_DATABASE=${{ secrets.DB_DATABASE_SANTEYALLA }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME_SANTEYALLA }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_SANTEYALLA }}" >> .env
          # ... Ajoutez d'autres variables d'environnement si nécessaire

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
